root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/optimus ./cmd/optimus"
bin = "./tmp/optimus"
include_ext = ["go", "yaml"]
exclude_dir = ["tmp", "bin", "migrations", "web"]
delay = 500
kill_delay = "2s"
